baseURL = "/"
languageCode = "en-us"
title = "CÔNG TY TNHH MỘT THÀNH VIÊN QUẢNG CÁO VÀ THƯƠNG MẠI ĐÔNG NAM Á"
theme = ""

[params]
  google_analytics_id=""

  # Preview container button text
    buttontext = "Liên hệ ngay"

  [params.homepage_meta_tags]
    meta_description = "Thiết kế, thi công, lắp đặt các loại biển quảng cáo chuyên nghiệp"
    meta_og_title = "CÔNG TY TNHH MỘT THÀNH VIÊN QUẢNG CÁO VÀ THƯƠNG MẠI ĐÔNG NAM Á"
    meta_og_type = "website"
    meta_og_url = "https://hugo-serif.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Serif is a beautiful small business theme for Hugo (Static Site Generator). It contains content types for the archetypical small business website. The theme is fully responsive, blazing fast and artfully illustrated."

# Main Menu
[[menu.main]]
	name = "Danh mục"
	url = "/services/"
    weight = 1

[[menu.main]]
	name = "Về chúng tôi"
	url = "/about/"
	weight = 2

[[menu.main]]
    name = "Liên hệ"
    url = "/contact/"
    weight = 3

[[menu.main]]
    name = "Tuyển dụng"
    url = "/recruits/"
    weight = 4

# Footer Menu
[[menu.footer]]
	name = "Trang chủ"
	url = "/"
    weight = 1

[[menu.footer]]
	name = "Liên hệ"
	url = "/contact/"
    weight = 2