baseURL = "/"
languageCode = "en-us"
title = "Công ty TNHH một thành viên quảng cáo và thương mại Đông Nam Á"
theme = ""
summaryLength = "10"
paginate = 6

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML"]

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/headroom/headroom.js"
  [[params.plugins.js]]
  URL = "plugins/masonry/masonry.js"
  [[params.plugins.js]]
  URL = "plugins/reading-time/readingTime.min.js"
  [[params.plugins.js]]
  URL = "plugins/smooth-scroll/smooth-scroll.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  

# Main Menu
[[menu.main]]
	name = "Trang chủ"
	url = "/"
    weight = 1

[[menu.main]]
	name = "Danh mục"
	url = "/services/"
    weight = 2

[[menu.main]]
	name = "Về chúng tôi"
	url = "/about/"
	weight = 3

[[menu.main]]
    name = "Liên hệ"
    url = "/contact/"
    weight = 4

[[menu.main]]
    name = "Tuyển dụng"
    url = "/recruits/"
    weight = 5

# Footer Menu
[[menu.footer]]
	name = "Trang chủ"
	url = "/"
    weight = 1

[[menu.footer]]
	name = "Liên hệ"
	url = "/contact/"
    weight = 2


[params]

  # Preview container button text
    buttontext = "Liên hệ ngay"

logo = "images/logo.png"
home = "Trang chủ"
# hompage layout ( two layout is available,  you can set the another layout by change the value of homeLayoutToggle "true" to "false")
homeLayoutToggle = true
# Meta data
description = "This is meta description"
# about author
author = "Themefisher"
authorImage = "images/banner-img.png"
shortDescription = "I’m a Freelance Interactive Art Director based in France. Focusing across branding and identity, digital and print."
# Contact Form Action
contactFormAction = "#"
# Google Analitycs
googleAnalitycsID = "Your ID"
# copyright
copyright = "a theme by [themefisher.com](themefisher.com)"

  # Preloader
  [params.preloader]
  enable = true
  
  # search
  [params.search]
  enable = true

  # footer
  [params.footer]

    #address
    [[params.footer.addresses]]
    address = "Thành phố Hải Dương"
    
    [[params.footer.addresses]]
    address = "6 rip carl Avenue CA 90733"

    
    #contact information
    [[params.footer.contacts]]
    contactInfo = "Tel: +90 000 333 22"
    
    [[params.footer.contacts]]
    contactInfo = "Mail: exmaple@ymail.com"


  # social site
  [[params.social]]
  icon = "ti-facebook"
  URL = "#"
  
  [[params.social]]
  icon = "ti-twitter-alt"
  URL = "#"
  
  [[params.social]]
  icon = "ti-linkedin"
  URL = "#"
  
  [[params.social]]
  icon = "ti-github"
  URL = "#"